### ISSUE TITLE
Geoform code question in Coos Bay NW arm

### ISSUE THREAD

**Issue by jrombouts1** [orcoastalmgmt/cmecs#3]
These areas are g318 ; Fill in Phase I. The imagery underneath suggest they may not be. 
Also, there is a code for pavement : g144

![northwest arm overview](https://cloud.githubusercontent.com/assets/11383901/24169347/90c604c8-0e3a-11e7-934c-2ac9bb2f9d27.jpg)
![geoform g318 fill](https://cloud.githubusercontent.com/assets/11383901/24170592/a2422aa2-0e3e-11e7-8218-c7f5734ae092.jpg)
![geoform g318 fill jpg imagery only](https://cloud.githubusercontent.com/assets/11383901/24170644/be7d5c32-0e3e-11e7-9dea-32c77f06d60b.jpg)

**Comment by tchaddad** [comment]
Thanks Jane - I gave this a label of Substrate component, but if you were looking at Geoform component you can go ahead and switch to the appropriate Geoform component label...

**Comment by jrombouts1** [comment]
No Thanks for doing that. I was trying to add labels but I can't seem to get to the correct format. I was just writing you an e-mail about that. I'll give more info there.

**Comment by tchaddad** [comment]
Now that we've confirmed that we are talking about the Geoform Component, I can address the comment about "Pavement Area". I'm pasting the definition below:

> _Geoform: Pavement Area (Levels 1 & 2) – Flat (or gently sloping), low-relief, solid, carbonate rock with little or no fine-scale rugosity. These areas can be covered with algae, hard coral, gorgonians, zooanthids, or other sessile vertebrates; the coverage may be dense enough to partially obscure the underlying surface. On less colonized pavement features, rock may be covered by a thin sand veneer (Kendall et al. 2001)._

I think this definition makes clear that it is not appropriate for these areas, as it is a marine geoform definition
