### ISSUE TITLE
Topology errors in Substrate Layer

### ISSUE THREAD

**Issue by cybersea** [orcoastalmgmt/cmecs#34]
Found and fixed topology errors in substrate component layer with ArcGIS Fix Geometry tool.  Report attached.
[Substrate_Component_DRAFT_20180308_errors.txt](https://github.com/orcoastalmgmt/cmecs/files/1830767/Substrate_Component_DRAFT_20180308_errors.txt)

**Comment by tchaddad** [comment]
resolved
