### ISSUE TITLE
Geoform codes do not match national code list

### ISSUE THREAD

**Issue by cybersea** [orcoastalmgmt/cmecs#35]
The geoform codes do not match codes from a spreadsheet found on the national [CMECS website](https://iocm.noaa.gov/cmecs/using-cmecs.html).   Suggest updating codes to national standard for consistency.

https://iocm.noaa.gov/cmecs/documents/CMECS-CODES-20160721-Excel.xlsx

**Comment by tchaddad** [comment]
Yeah - this one is puzzling, Our database also came from NOAA, but not sure what changed about geoform codes...

**Comment by tchaddad** [comment]
I've cross-walked these to the file you linked, although I'm still puzzled as to why these would have changed. Will add a separate ticket to update our local CMECS database of codes.
