### ISSUE TITLE
Found many questionable small polygons in Aquatic System layer due to Modifier

### ISSUE THREAD

**Issue by cybersea** [orcoastalmgmt/cmecs#36]
There seem to be numerous small polygons caused by the addition of the Diked modifier, but in a very limited visual review, many of these polygons do not appear to correspond to any identifiable features on an aerial photo.  They do not look like misalignment of shoreline boundaries either.   Not sure how they were generated, but may need a bit of a review

**Comment by tchaddad** [comment]
Are the polygons shown in https://github.com/orcoastalmgmt/cmecs/issues/5 an example of what is described here?

**Comment by tchaddad** [comment]
should be resolved now.
