### ISSUE TITLE
Some Biotic records missing attribute values higher in the hierarchy

### ISSUE THREAD

**Issue by cybersea** [orcoastalmgmt/cmecs#44]
For example, for forested wetlands, there are some entries where BC_SUBCLASS06 = 2.8.1, but the corresponding BC_CLASS08 is blank.  If I understand the data/attributes correctly, in this case, BC_CLASS08 should = 2.8.

There is a similar example with BC_SUBCLASS04 = 2.6.1 and BC_CLASS06 is blank.

Maybe layer-wide process/script to check for this kind of thing?

**Comment by tchaddad** [comment]
fixed
